"""
Script de uso unico: genera notebooks/01b_eda_fase2_ciudades.ipynb
Fase 2 del EDA: que nos dicen los datos reales de las 55 ciudades.
"""
import json
import uuid
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

def cid():
    return uuid.uuid4().hex[:8]

def code(lines):
    return {"cell_type": "code", "execution_count": None, "id": cid(),
            "metadata": {}, "outputs": [], "source": lines}

def md(lines):
    return {"cell_type": "markdown", "id": cid(), "metadata": {}, "source": lines}

cells = []

# ─────────────────────────────────────────────────────────────────────────────
# TITULO
# ─────────────────────────────────────────────────────────────────────────────
cells.append(md([
    "# NomadOptima — Notebook 01b: EDA de Datos de Entrada\n",
    "## Fase 2: ¿Qué nos dicen los datos reales de las 55 ciudades?\n",
    "\n",
    "**Objetivo:** Analizar el contenido del dataset `city_features.csv` para entender\n",
    "distribuciones, relaciones entre features, perfil de cada ciudad y estructura\n",
    "de clustering. Valida que los datos tienen sentido antes de generar perfiles\n",
    "sintéticos y entrenar el modelo.\n",
    "\n",
    "**Bloques:**\n",
    "- A: Estadísticas básicas\n",
    "- B: Distribuciones\n",
    "- C: Relaciones entre features\n",
    "- D: Perfil de ciudades\n",
    "- E: Estructura y clustering\n",
]))

# ─────────────────────────────────────────────────────────────────────────────
# IMPORTS
# ─────────────────────────────────────────────────────────────────────────────
cells.append(code([
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import matplotlib.patches as mpatches\n",
    "import matplotlib.cm as cm\n",
    "import seaborn as sns\n",
    "from pathlib import Path\n",
    "from sklearn.preprocessing import MinMaxScaler, StandardScaler\n",
    "from sklearn.decomposition import PCA\n",
    "from sklearn.cluster import KMeans\n",
    "from sklearn.metrics import silhouette_score, davies_bouldin_score\n",
    "from scipy.cluster.hierarchy import dendrogram, linkage\n",
    "from scipy.spatial.distance import pdist\n",
    "import umap\n",
    "import hdbscan\n",
    "import warnings\n",
    "warnings.filterwarnings('ignore')\n",
    "\n",
    "plt.rcParams['figure.figsize'] = (14, 7)\n",
    "plt.rcParams['font.size'] = 11\n",
    "plt.rcParams['axes.spines.top'] = False\n",
    "plt.rcParams['axes.spines.right'] = False\n",
    "\n",
    "ROOT = Path('..')\n",
    "df_raw = pd.read_csv(ROOT / 'data' / 'processed' / 'city_features.csv', index_col=0)\n",
    "\n",
    "# Solo features numericas para analisis\n",
    "num_df = df_raw.select_dtypes(include='number').copy()\n",
    "\n",
    "# Clasificacion de columnas por fuente (consistente con Fase 1)\n",
    "FUENTES = {\n",
    "    'Google Places': [c for c in num_df.columns if c.startswith('city_gp_')],\n",
    "    'OpenStreetMap': [c for c in num_df.columns if c in [\n",
    "        'city_beaches','city_parks','city_gyms','city_restaurants','city_cafes',\n",
    "        'city_playgrounds','city_schools','city_kindergartens','city_childcare',\n",
    "        'city_dog_areas','city_coworking_osm','city_public_transport',\n",
    "        'city_bicycle_lanes','city_pharmacies','city_hospitals'\n",
    "    ]],\n",
    "    'Numbeo':        [c for c in num_df.columns if c in [\n",
    "        'city_coste_vida_estimado','city_alquiler_1br_centro',\n",
    "        'city_transport_monthly','city_meal_cheap','city_quality_of_life'\n",
    "    ]],\n",
    "    'Clima':         [c for c in num_df.columns if c in [\n",
    "        'city_temp_actual_c','city_temp_media_anual','city_dias_sol_anual',\n",
    "        'city_temp_media_norm','city_dias_sol_norm'\n",
    "    ]],\n",
    "    'Speedtest':     ['city_internet_mbps'],\n",
    "    'RestCountries': [c for c in num_df.columns if 'idioma' in c\n",
    "                      or c in ['city_schengen','city_moneda_eur']],\n",
    "    'Wikidata':      ['city_population','city_area_km2','city_population_density'],\n",
    "    'Derivadas':     ['city_coste_invertido'],\n",
    "}\n",
    "\n",
    "# Regiones para colorear graficos\n",
    "REGIONES = {\n",
    "    'Europa Occidental':  ['Barcelona','Madrid','Valencia','Sevilla','Malaga','Alicante',\n",
    "                           'Granada','Tarifa','Fuerteventura','Las_Palmas','Faro','Lisboa',\n",
    "                           'Porto','Paris','Bordeaux','Chamonix','Amsterdam','London',\n",
    "                           'Berlin','Munich','Vienna','Milan','Napoles','Roma','Dublin',\n",
    "                           'Stockholm','Andorra','Innsbruck'],\n",
    "    'Europa del Este':    ['Prague','Warsaw','Krakow','Budapest','Bucharest','Sofia',\n",
    "                           'Belgrade','Tallinn','Tbilisi'],\n",
    "    'Asia':               ['Bangkok','Chiang_Mai','Bali','Da_Nang','Kuala_Lumpur','Dubai'],\n",
    "    'Latinoamerica':      ['Medellin','Bogota','Cartagena','Mexico_City','Playa_Del_Carmen',\n",
    "                           'Lima','Santiago','Buenos_Aires','Montevideo'],\n",
    "    'Africa/Oriente':     ['Marrakech','Dakhla','Essaouira'],\n",
    "    'Atenas':             ['Atenas'],\n",
    "}\n",
    "COLORES_REGION = {\n",
    "    'Europa Occidental': '#4285F4',\n",
    "    'Europa del Este':   '#34A853',\n",
    "    'Asia':              '#EA4335',\n",
    "    'Latinoamerica':     '#FBBC05',\n",
    "    'Africa/Oriente':    '#9C27B0',\n",
    "    'Atenas':            '#00BCD4',\n",
    "}\n",
    "\n",
    "def color_ciudad(ciudad):\n",
    "    for region, ciudades in REGIONES.items():\n",
    "        if ciudad in ciudades:\n",
    "            return COLORES_REGION[region]\n",
    "    return '#BDBDBD'\n",
    "\n",
    "print(f'Dataset: {df_raw.shape[0]} ciudades x {df_raw.shape[1]} features')\n",
    "print(f'Features numericas para analisis: {num_df.shape[1]}')\n",
]))

# ─────────────────────────────────────────────────────────────────────────────
# BLOQUE A — ESTADÍSTICAS BÁSICAS
# ─────────────────────────────────────────────────────────────────────────────
cells.append(md([
    "---\n",
    "## Bloque A — Estadísticas básicas\n",
]))

# Paso 1: describe()
cells.append(md(["### Paso 1: describe() — estadísticas básicas por feature\n"]))

cells.append(code([
    "# Paso 1 — describe() resumido por fuente\n",
    "# Mostramos: media, std, min, max para features representativas de cada fuente\n",
    "\n",
    "REPR = [\n",
    "    'city_gp_restaurant', 'city_gp_museum', 'city_gp_gym', 'city_gp_coworking',\n",
    "    'city_gp_surf_school', 'city_gp_ski_resort', 'city_gp_spa', 'city_gp_hostel',\n",
    "    'city_restaurants', 'city_parks', 'city_hospitals', 'city_childcare',\n",
    "    'city_alquiler_1br_centro', 'city_meal_cheap', 'city_quality_of_life',\n",
    "    'city_temp_media_anual', 'city_dias_sol_anual', 'city_internet_mbps',\n",
    "    'city_population_density', 'city_coste_vida_estimado',\n",
    "]\n",
    "desc = num_df[REPR].describe().round(1)\n",
    "print('=== ESTADISTICAS BASICAS (features representativas) ===')\n",
    "print(desc.to_string())\n",
    "print()\n",
    "print('Rango de coste de vida:')\n",
    "coste = num_df['city_coste_vida_estimado'].sort_values()\n",
    "print(f'  Mas barata: {coste.index[0]} ({coste.iloc[0]:.0f} EUR/mes)')\n",
    "print(f'  Mas cara:   {coste.index[-1]} ({coste.iloc[-1]:.0f} EUR/mes)')\n",
    "print(f'  Media:      {coste.mean():.0f} EUR/mes')\n",
    "print()\n",
    "print('Rango de temperatura media anual:')\n",
    "temp = num_df['city_temp_media_anual'].sort_values()\n",
    "print(f'  Mas fria:   {temp.index[0]} ({temp.iloc[0]:.1f} C)')\n",
    "print(f'  Mas calida: {temp.index[-1]} ({temp.iloc[-1]:.1f} C)')\n",
]))

cells.append(md([
    "```\n",
    "PARA QUE SIRVE ESTA TABLA:\n",
    "  describe() muestra las estadisticas basicas de cada feature numerica:\n",
    "  count (cuantas ciudades tienen datos), mean (media), std (desviacion estandar),\n",
    "  min, max, y los percentiles 25/50/75.\n",
    "  Es el primer paso de cualquier EDA: entender la escala y variabilidad de los datos.\n",
    "\n",
    "QUE NOS ESTA MOSTRANDO:\n",
    "  - Las features tienen escalas muy distintas: city_restaurants puede llegar a 80\n",
    "    mientras city_quality_of_life esta entre 0 y 200, y city_alquiler entre 350 y 2500.\n",
    "  - La std alta en coste de vida indica gran variabilidad entre ciudades\n",
    "    (Tbilisi ~700 EUR vs Chamonix ~2100 EUR). Eso es bueno para el modelo.\n",
    "  - city_internet_mbps tiene muchos ceros (ciudades sin dato). La media\n",
    "    esta sesgada hacia abajo por esos ceros.\n",
    "\n",
    "DECISION / IMPLICACION PARA EL MODELO:\n",
    "  - Las escalas distintas confirman que necesitamos normalizar (MinMaxScaler)\n",
    "    antes de calcular Cosine Similarity. Sin normalizacion, city_alquiler\n",
    "    dominaria el vector de ciudad solo por tener valores 100x mayores.\n",
    "  - La alta variabilidad en coste y clima es positiva: significa que el modelo\n",
    "    puede diferenciar bien entre ciudades en esas dimensiones.\n",
    "```\n",
]))

# Paso 2: Heatmap ceros por ciudad
cells.append(md(["### Paso 2: Mapa de ceros por ciudad — ¿dónde faltan datos?\n"]))

cells.append(code([
    "# Paso 2 — Heatmap de % de features a cero por ciudad\n",
    "# Mas especifico que Fase 1: aqui vemos dentro de cada fuente\n",
    "\n",
    "fig, axes = plt.subplots(1, len(FUENTES), figsize=(20, 12),\n",
    "                          gridspec_kw={'width_ratios': [len(v) for v in FUENTES.values()]})\n",
    "\n",
    "for ax, (fuente, cols) in zip(axes, FUENTES.items()):\n",
    "    num_cols = [c for c in cols if c in num_df.columns]\n",
    "    if not num_cols:\n",
    "        ax.axis('off')\n",
    "        continue\n",
    "    sub = (num_df[num_cols] == 0).astype(int)\n",
    "    short_cols = [c.replace('city_gp_','gp_').replace('city_idioma_','id_').replace('city_','') for c in num_cols]\n",
    "    sub.columns = short_cols\n",
    "    sns.heatmap(sub, ax=ax, cmap='RdYlGn_r', vmin=0, vmax=1,\n",
    "                cbar=False, linewidths=0.2, linecolor='white',\n",
    "                yticklabels=(ax == axes[0]))\n",
    "    ax.set_title(fuente, fontweight='bold', fontsize=9, rotation=0)\n",
    "    ax.set_xticklabels(ax.get_xticklabels(), rotation=90, fontsize=6)\n",
    "    ax.set_yticklabels(ax.get_yticklabels(), fontsize=7)\n",
    "\n",
    "fig.suptitle('Mapa de ceros por ciudad y fuente\\n'\n",
    "             '(verde = tiene datos, rojo = valor = 0)',\n",
    "             fontweight='bold', fontsize=13, y=1.01)\n",
    "plt.tight_layout()\n",
    "plt.savefig('../data/processed/eda_fase2_ceros_heatmap.png', dpi=150, bbox_inches='tight')\n",
    "plt.show()\n",
    "\n",
    "# Resumen: % de ceros por ciudad\n",
    "pct_ceros_ciudad = (num_df == 0).mean(axis=1).sort_values(ascending=False)\n",
    "print('Top 10 ciudades con mas ceros:')\n",
    "for c, pct in pct_ceros_ciudad.head(10).items():\n",
    "    print(f'  {c:<25}: {pct:.0%} de features a cero')\n",
]))

cells.append(md([
    "```\n",
    "PARA QUE SIRVE ESTE GRAFICO:\n",
    "  Muestra para cada ciudad (fila) y cada feature (columna) si el valor es cero\n",
    "  (rojo) o tiene datos (verde). Se divide por fuente para ver rapidamente\n",
    "  que fuente falla en que ciudades.\n",
    "\n",
    "QUE NOS ESTA MOSTRANDO:\n",
    "  - Da_Nang aparece casi completamente roja — confirma que debe eliminarse.\n",
    "  - La columna de Speedtest es casi toda roja: solo 12 ciudades tienen dato.\n",
    "  - Las columnas de idioma nativo especifico (holandes, checo, hungaro...)\n",
    "    son rojas en casi todas las ciudades excepto en la 1-2 ciudades afectadas.\n",
    "  - Las features GP tienen buena cobertura general (verde dominante).\n",
    "\n",
    "DECISION / IMPLICACION PARA EL MODELO:\n",
    "  - Este grafico justifica visualmente las mismas decisiones de Fase 1,\n",
    "    pero ahora a nivel de feature individual, no solo de fuente.\n",
    "  - Antes de entrenar: eliminar Da_Nang y las 8 features completamente vacias.\n",
    "```\n",
]))

# ─────────────────────────────────────────────────────────────────────────────
# BLOQUE B — DISTRIBUCIONES
# ─────────────────────────────────────────────────────────────────────────────
cells.append(md([
    "---\n",
    "## Bloque B — Distribuciones\n",
]))

# Paso 3: Histogramas + KDE
cells.append(md(["### Paso 3: Histogramas + KDE — distribución de features clave\n"]))

cells.append(code([
    "# Paso 3 — Histogramas + KDE para features clave (una por categoria)\n",
    "# KDE = Kernel Density Estimate: curva suave que muestra la forma de la distribucion\n",
    "\n",
    "FEATURES_REPR = {\n",
    "    'Coste vida (EUR/mes)':    'city_coste_vida_estimado',\n",
    "    'Alquiler 1BR (EUR/mes)':  'city_alquiler_1br_centro',\n",
    "    'Calidad de vida (indice)':'city_quality_of_life',\n",
    "    'Temp. media anual (C)':   'city_temp_media_anual',\n",
    "    'Dias de sol':             'city_dias_sol_anual',\n",
    "    'Internet (Mbps)':         'city_internet_mbps',\n",
    "    'GP restaurantes':         'city_gp_restaurant',\n",
    "    'GP gimnasios':            'city_gp_gym',\n",
    "    'GP escuelas surf':        'city_gp_surf_school',\n",
    "    'GP ski resort':           'city_gp_ski_resort',\n",
    "    'GP museos':               'city_gp_museum',\n",
    "    'GP coworkings':           'city_gp_coworking',\n",
    "    'OSM playas':              'city_beaches',\n",
    "    'OSM parques':             'city_parks',\n",
    "    'Densidad pob. (hab/km2)': 'city_population_density',\n",
    "}\n",
    "\n",
    "fig, axes = plt.subplots(3, 5, figsize=(20, 12))\n",
    "axes_flat = axes.flatten()\n",
    "\n",
    "for i, (label, col) in enumerate(FEATURES_REPR.items()):\n",
    "    ax = axes_flat[i]\n",
    "    datos = num_df[col].dropna()\n",
    "    datos_nonzero = datos[datos > 0]\n",
    "\n",
    "    # Histograma con todos los valores\n",
    "    ax.hist(datos, bins=15, color='#4285F4', alpha=0.6, edgecolor='white',\n",
    "            label=f'n={len(datos)}')\n",
    "\n",
    "    # KDE solo si hay suficiente variabilidad\n",
    "    if datos.std() > 0 and len(datos_nonzero) > 5:\n",
    "        from scipy.stats import gaussian_kde\n",
    "        kde = gaussian_kde(datos_nonzero)\n",
    "        x_range = np.linspace(datos.min(), datos.max(), 100)\n",
    "        ax2 = ax.twinx()\n",
    "        ax2.plot(x_range, kde(x_range), color='#EA4335', linewidth=2)\n",
    "        ax2.set_yticks([])\n",
    "        ax2.spines['top'].set_visible(False)\n",
    "        ax2.spines['right'].set_visible(False)\n",
    "\n",
    "    # Linea de la media\n",
    "    ax.axvline(datos.mean(), color='black', linestyle='--', alpha=0.6, linewidth=1)\n",
    "    ax.set_title(label, fontsize=9, fontweight='bold')\n",
    "    ax.set_xlabel('')\n",
    "    ax.tick_params(labelsize=7)\n",
    "\n",
    "fig.suptitle('Distribucion de features clave (barra=histograma, curva roja=KDE)',\n",
    "             fontweight='bold', fontsize=13)\n",
    "plt.tight_layout()\n",
    "plt.savefig('../data/processed/eda_fase2_histogramas.png', dpi=150, bbox_inches='tight')\n",
    "plt.show()\n",
]))

cells.append(md([
    "```\n",
    "PARA QUE SIRVE ESTE GRAFICO:\n",
    "  El histograma muestra cuantas ciudades tienen cada valor.\n",
    "  La curva KDE (Kernel Density Estimate) es una version suavizada del histograma\n",
    "  que facilita ver la forma de la distribucion: si es simetrica, sesgada a la\n",
    "  derecha, bimodal (dos picos), etc.\n",
    "  La linea punteada negra es la media.\n",
    "\n",
    "QUE NOS ESTA MOSTRANDO:\n",
    "  - Coste de vida: distribucion sesgada a la derecha. La mayoria de ciudades\n",
    "    son asequibles (700-1200 EUR) pero hay un grupo caro (Londres, Chamonix, Zurich).\n",
    "  - Temperatura: dos grupos naturales — ciudades frias (8-12 C, Europa Norte)\n",
    "    y calidas (18-28 C, Sur + Asia). Buena separacion para el modelo.\n",
    "  - GP ski resort: distribucion extrema — la mayoria tiene 0, solo 3 ciudades\n",
    "    tienen valores altos (Chamonix, Innsbruck, Andorra). Correcto.\n",
    "  - Internet (Mbps): pico en 0 (43 ciudades sin dato) + distribucion real\n",
    "    para las 12 con dato. El cero no significa velocidad cero sino dato ausente.\n",
    "  - GP restaurantes: distribucion uniforme entre 15-40. El cap() funciona\n",
    "    correctamente — ningun valor supera 40.\n",
    "\n",
    "DECISION / IMPLICACION PARA EL MODELO:\n",
    "  - Las distribuciones bimodales (temperatura, coste) son excelentes para el\n",
    "    modelo: permiten diferenciar claramente entre tipos de destino.\n",
    "  - Las distribuciones con muchos ceros (ski_resort, internet) tienen poco\n",
    "    poder predictivo para la mayoria de ciudades.\n",
    "  - La curva KDE es util en entrevistas para explicar la forma de los datos\n",
    "    antes de modelar.\n",
    "```\n",
]))

# Paso 4: Boxplots por categoria
cells.append(md(["### Paso 4: Boxplots por categoría — variabilidad entre ciudades\n"]))

cells.append(code([
    "# Paso 4 — Boxplots de features normalizadas agrupadas por categoria\n",
    "# Normalizamos a 0-1 para poder comparar features de escalas distintas en el mismo eje\n",
    "\n",
    "CATEGORIAS_BOX = {\n",
    "    'Gastronomia':  ['city_gp_restaurant','city_gp_fine_dining','city_gp_vegan',\n",
    "                     'city_gp_coffee_shop','city_gp_wine_bar','city_restaurants'],\n",
    "    'Deporte agua': ['city_gp_surf_school','city_gp_kitesurfing','city_gp_windsurfing',\n",
    "                     'city_gp_wingfoil','city_gp_marina','city_beaches'],\n",
    "    'Deporte mnt':  ['city_gp_ski_resort','city_gp_snowpark','city_gp_ski_touring',\n",
    "                     'city_gp_hiking_area','city_gp_adventure_sports'],\n",
    "    'Cultura':      ['city_gp_museum','city_gp_historical_landmark','city_gp_monument',\n",
    "                     'city_gp_art_gallery','city_gp_performing_arts'],\n",
    "    'Vida Nocturna':['city_gp_night_club','city_gp_bar','city_gp_pub',\n",
    "                     'city_gp_cocktail_bar','city_gp_live_music'],\n",
    "    'Nomada Dig.':  ['city_gp_coworking','city_gp_coliving','city_gp_tech_hub',\n",
    "                     'city_internet_mbps','city_gp_library'],\n",
    "    'Bienestar':    ['city_gp_spa','city_gp_yoga_studio','city_gp_sauna',\n",
    "                     'city_gp_massage','city_gp_thermal_bath'],\n",
    "    'Familia':      ['city_playgrounds','city_schools','city_childcare',\n",
    "                     'city_gp_preschool','city_gp_international_school'],\n",
    "}\n",
    "\n",
    "scaler_box = MinMaxScaler()\n",
    "num_norm = pd.DataFrame(\n",
    "    scaler_box.fit_transform(num_df),\n",
    "    index=num_df.index, columns=num_df.columns\n",
    ")\n",
    "\n",
    "fig, axes = plt.subplots(2, 4, figsize=(20, 10))\n",
    "axes_flat = axes.flatten()\n",
    "\n",
    "for i, (cat, cols) in enumerate(CATEGORIAS_BOX.items()):\n",
    "    ax = axes_flat[i]\n",
    "    cols_ok = [c for c in cols if c in num_norm.columns]\n",
    "    data_box = [num_norm[c].values for c in cols_ok]\n",
    "    short_labels = [c.replace('city_gp_','gp_').replace('city_','') for c in cols_ok]\n",
    "\n",
    "    bp = ax.boxplot(data_box, patch_artist=True, medianprops=dict(color='black', linewidth=2))\n",
    "    for patch in bp['boxes']:\n",
    "        patch.set_facecolor('#4285F480')\n",
    "\n",
    "    ax.set_xticks(range(1, len(cols_ok)+1))\n",
    "    ax.set_xticklabels(short_labels, rotation=45, ha='right', fontsize=8)\n",
    "    ax.set_ylabel('Valor norm. [0-1]')\n",
    "    ax.set_title(cat, fontweight='bold')\n",
    "    ax.set_ylim(-0.05, 1.1)\n",
    "\n",
    "fig.suptitle('Variabilidad por categoria (valores normalizados 0-1)\\n'\n",
    "             'Caja = percentiles 25-75. Linea central = mediana. Puntos = outliers',\n",
    "             fontweight='bold', fontsize=13)\n",
    "plt.tight_layout()\n",
    "plt.savefig('../data/processed/eda_fase2_boxplots.png', dpi=150, bbox_inches='tight')\n",
    "plt.show()\n",
]))

cells.append(md([
    "```\n",
    "PARA QUE SIRVE ESTE GRAFICO:\n",
    "  Un boxplot muestra la distribucion de una variable en 5 numeros:\n",
    "  minimo, percentil 25, mediana (linea central), percentil 75, maximo.\n",
    "  Los puntos fuera de los bigotes son outliers (ciudades con valores extremos).\n",
    "  Al normalizar a 0-1 podemos comparar features de escalas distintas en el mismo eje.\n",
    "\n",
    "QUE NOS ESTA MOSTRANDO:\n",
    "  - Deporte agua: gp_kitesurfing y gp_windsurfing tienen la mediana en 0 con\n",
    "    pocos outliers altos (Tarifa, Fuerteventura, Dakhla). Correcto para deportes\n",
    "    especializados que solo existen en destinos concretos.\n",
    "  - Deporte montana: ski_resort tiene casi todas las ciudades en 0 con 3 outliers\n",
    "    extremos (Chamonix, Innsbruck, Andorra). El modelo aprende a diferenciar bien.\n",
    "  - Gastronomia: distribucion mas uniforme — la mayoria de ciudades tienen\n",
    "    restaurantes y cafes (mediana alta). Menos diferenciadora para el modelo.\n",
    "  - Cultura: museos y monumentos tienen cajas amplias — buena variabilidad\n",
    "    entre ciudades. Roma y Paris sobresalen como outliers en la parte alta.\n",
    "\n",
    "DECISION / IMPLICACION PARA EL MODELO:\n",
    "  - Features con mediana en 0 y pocos outliers altos (ski, kite) son muy\n",
    "    discriminativas: solo unas pocas ciudades destacan. El modelo las usara\n",
    "    para separar destinos especializados de los generalistas.\n",
    "  - Features con distribucion uniforme y alta (gastronomia basica) tienen\n",
    "    menos poder de separacion — todas las ciudades son 'parecidas' en eso.\n",
    "  - Los outliers visibles en los boxplots son las ciudades 'estrella' de cada\n",
    "    categoria: exactamente lo que queremos recomendar para perfiles especializados.\n",
    "```\n",
]))

# ─────────────────────────────────────────────────────────────────────────────
# BLOQUE C — RELACIONES ENTRE FEATURES
# ─────────────────────────────────────────────────────────────────────────────
cells.append(md([
    "---\n",
    "## Bloque C — Relaciones entre features\n",
]))

# Paso 5: Correlaciones
cells.append(md(["### Paso 5: Correlaciones — ¿hay features redundantes?\n"]))

cells.append(code([
    "# Paso 5 — Heatmap de correlaciones Pearson entre features clave\n",
    "# Pearson mide si dos variables se mueven juntas (correlacion positiva)\n",
    "# o en sentido contrario (negativa). Rango: -1 a +1.\n",
    "# Correlacion alta (>0.8): las features son redundantes, miden lo mismo.\n",
    "\n",
    "FEATURES_CORR = [\n",
    "    'city_coste_vida_estimado', 'city_alquiler_1br_centro', 'city_meal_cheap',\n",
    "    'city_quality_of_life', 'city_temp_media_anual', 'city_dias_sol_anual',\n",
    "    'city_population_density', 'city_gp_restaurant', 'city_gp_museum',\n",
    "    'city_gp_gym', 'city_gp_coworking', 'city_gp_surf_school',\n",
    "    'city_gp_ski_resort', 'city_gp_night_club', 'city_gp_spa',\n",
    "    'city_gp_hostel', 'city_restaurants', 'city_parks', 'city_hospitals',\n",
    "    'city_childcare', 'city_beaches', 'city_internet_mbps',\n",
    "]\n",
    "\n",
    "corr = num_df[FEATURES_CORR].corr(method='pearson')\n",
    "short_names = [c.replace('city_gp_','gp_').replace('city_','') for c in FEATURES_CORR]\n",
    "corr.index = short_names\n",
    "corr.columns = short_names\n",
    "\n",
    "fig, ax = plt.subplots(figsize=(16, 14))\n",
    "mask = np.triu(np.ones_like(corr, dtype=bool), k=1)\n",
    "sns.heatmap(corr, ax=ax, cmap='RdBu_r', center=0, vmin=-1, vmax=1,\n",
    "            annot=True, fmt='.2f', fontsize=7,\n",
    "            linewidths=0.5, linecolor='white',\n",
    "            square=True, cbar_kws={'shrink': 0.6})\n",
    "ax.set_title('Correlaciones Pearson entre features clave\\n'\n",
    "             'Azul = correlacion positiva. Rojo = negativa. Blanco = sin correlacion',\n",
    "             fontweight='bold', pad=15)\n",
    "plt.tight_layout()\n",
    "plt.savefig('../data/processed/eda_fase2_correlaciones.png', dpi=150, bbox_inches='tight')\n",
    "plt.show()\n",
    "\n",
    "# Pares con correlacion muy alta\n",
    "print('Pares con correlacion > 0.75 (posible redundancia):')\n",
    "for i in range(len(corr.columns)):\n",
    "    for j in range(i+1, len(corr.columns)):\n",
    "        val = corr.iloc[i, j]\n",
    "        if abs(val) > 0.75:\n",
    "            print(f'  {corr.columns[i]:<30} <-> {corr.columns[j]:<30}: {val:.2f}')\n",
]))

cells.append(md([
    "```\n",
    "PARA QUE SIRVE ESTE GRAFICO:\n",
    "  El heatmap de correlaciones muestra si dos features se mueven juntas.\n",
    "  Azul intenso = correlacion positiva alta (cuando una sube, la otra tambien).\n",
    "  Rojo intenso = correlacion negativa (cuando una sube, la otra baja).\n",
    "  Blanco = sin correlacion (son independientes).\n",
    "  En ML esto se llama multicolinealidad: si dos features estan muy correlacionadas,\n",
    "  una de ellas es redundante y podria eliminarse sin perder informacion.\n",
    "\n",
    "QUE NOS ESTA MOSTRANDO:\n",
    "  - coste_vida y alquiler tienen correlacion alta esperada (el alquiler\n",
    "    es el componente principal del coste total).\n",
    "  - restaurants (OSM) y gp_restaurant (GP) tienen correlacion moderada:\n",
    "    miden cosas similares pero no identicas (OSM es mas exhaustivo en\n",
    "    ciudades bien mapeadas, GP usa radio fijo).\n",
    "  - temp_media y dias_sol tienen correlacion positiva: ciudades calidas\n",
    "    tienden a tener mas sol. Logico geograficamente.\n",
    "  - ski_resort tiene correlacion negativa con temperatura: ciudades de\n",
    "    esqui son frias. Exactamente lo que esperabamos.\n",
    "\n",
    "DECISION / IMPLICACION PARA EL MODELO:\n",
    "  - LightGBM maneja bien la multicolinealidad, pero es bueno saberla.\n",
    "  - Las correlaciones muy altas (>0.9) entre features de la misma categoria\n",
    "    podrian eliminarse para reducir dimensionalidad. Para MVP se mantienen.\n",
    "  - La correlacion negativa entre ski y temperatura es un sanity check:\n",
    "    confirma que los datos tienen sentido geografico real.\n",
    "```\n",
]))

# Paso 6: Scatter coste vs calidad
cells.append(md(["### Paso 6: Scatter coste vs calidad de vida\n"]))

cells.append(code([
    "# Paso 6 — Scatter: coste de vida vs calidad de vida\n",
    "# Pregunta: las ciudades mas caras son siempre de mayor calidad?\n",
    "\n",
    "df_scatter = num_df[['city_coste_vida_estimado','city_quality_of_life',\n",
    "                       'city_temp_media_anual']].copy()\n",
    "df_scatter = df_scatter[df_scatter['city_quality_of_life'] > 0]\n",
    "df_scatter = df_scatter[df_scatter['city_coste_vida_estimado'] > 0]\n",
    "\n",
    "fig, ax = plt.subplots(figsize=(14, 9))\n",
    "\n",
    "for ciudad in df_scatter.index:\n",
    "    x = df_scatter.loc[ciudad, 'city_coste_vida_estimado']\n",
    "    y = df_scatter.loc[ciudad, 'city_quality_of_life']\n",
    "    color = color_ciudad(ciudad)\n",
    "    ax.scatter(x, y, color=color, s=80, zorder=3, alpha=0.85)\n",
    "    ax.annotate(ciudad.replace('_',' '), (x, y),\n",
    "                textcoords='offset points', xytext=(5, 3),\n",
    "                fontsize=7, alpha=0.85)\n",
    "\n",
    "# Linea de tendencia\n",
    "z = np.polyfit(df_scatter['city_coste_vida_estimado'],\n",
    "               df_scatter['city_quality_of_life'], 1)\n",
    "p = np.poly1d(z)\n",
    "x_line = np.linspace(df_scatter['city_coste_vida_estimado'].min(),\n",
    "                     df_scatter['city_coste_vida_estimado'].max(), 100)\n",
    "ax.plot(x_line, p(x_line), '--', color='gray', alpha=0.5, label='Tendencia lineal')\n",
    "\n",
    "# Leyenda regiones\n",
    "handles = [mpatches.Patch(color=c, label=r) for r, c in COLORES_REGION.items()]\n",
    "ax.legend(handles=handles, fontsize=9, loc='lower right')\n",
    "\n",
    "ax.set_xlabel('Coste de vida estimado (EUR/mes)', fontsize=11)\n",
    "ax.set_ylabel('Indice de calidad de vida (Numbeo)', fontsize=11)\n",
    "ax.set_title('Coste de vida vs Calidad de vida\\n'\n",
    "             '¿Las ciudades mas caras son siempre las mejores?',\n",
    "             fontweight='bold', pad=12)\n",
    "plt.tight_layout()\n",
    "plt.savefig('../data/processed/eda_fase2_coste_vs_calidad.png', dpi=150, bbox_inches='tight')\n",
    "plt.show()\n",
]))

cells.append(md([
    "```\n",
    "PARA QUE SIRVE ESTE GRAFICO:\n",
    "  Un scatter plot muestra la relacion entre dos variables: una en el eje X\n",
    "  y otra en el eje Y. Cada punto es una ciudad. Si los puntos forman una\n",
    "  diagonal ascendente, hay correlacion positiva.\n",
    "  Este grafico responde: al pagar mas, se vive mejor?\n",
    "\n",
    "QUE NOS ESTA MOSTRANDO:\n",
    "  - Hay correlacion positiva moderada: ciudades mas caras tienden a tener\n",
    "    mejor calidad de vida (eje Numbeo). Pero la dispersion es alta.\n",
    "  - Outliers 'valor': ciudades que tienen buena calidad de vida a bajo\n",
    "    coste. Medellin, Tbilisi, algunas ciudades del Este de Europa.\n",
    "    Estos son los destinos mas interesantes para nomadas digitales con\n",
    "    presupuesto medio.\n",
    "  - Outliers 'caro sin calidad': ciudades caras que no destacan en calidad.\n",
    "  - Las ciudades latinoamericanas (amarillo) tienen buena dispersion:\n",
    "    van desde muy baratas con calidad media hasta opciones sorprendentes.\n",
    "\n",
    "DECISION / IMPLICACION PARA EL MODELO:\n",
    "  - El scatter valida que city_coste_invertido (1 - coste normalizado) y\n",
    "    city_quality_of_life son features independientes y complementarias:\n",
    "    no miden lo mismo aunque esten correlacionadas.\n",
    "  - Los 'outliers valor' (baratos y buena calidad) seran las ciudades\n",
    "    recomendadas para perfiles con user_imp_coste alto. El modelo debe\n",
    "    capturar esa logica correctamente.\n",
    "```\n",
]))

# ─────────────────────────────────────────────────────────────────────────────
# BLOQUE D — PERFIL DE CIUDADES
# ─────────────────────────────────────────────────────────────────────────────
cells.append(md([
    "---\n",
    "## Bloque D — Perfil de ciudades\n",
]))

# Paso 7: Heatmap ciudad x feature
cells.append(md(["### Paso 7: Heatmap ciudad × feature normalizado — ¿son las ciudades distinguibles?\n"]))

cells.append(code([
    "# Paso 7 — Heatmap: 55 ciudades x features clave (normalizadas 0-1)\n",
    "# Si todas las filas son del mismo color, las ciudades son indistinguibles.\n",
    "# Si hay patrones claros, el modelo puede diferenciarlas.\n",
    "\n",
    "FEATURES_HEATMAP = [\n",
    "    'city_gp_surf_school', 'city_gp_kitesurfing', 'city_gp_windsurfing',\n",
    "    'city_gp_ski_resort', 'city_gp_snowpark',\n",
    "    'city_gp_museum', 'city_gp_art_gallery', 'city_gp_historical_landmark',\n",
    "    'city_gp_night_club', 'city_gp_bar', 'city_gp_live_music',\n",
    "    'city_gp_coworking', 'city_gp_coliving', 'city_gp_tech_hub',\n",
    "    'city_gp_spa', 'city_gp_yoga_studio', 'city_gp_thermal_bath',\n",
    "    'city_gp_restaurant', 'city_gp_fine_dining', 'city_gp_wine_bar',\n",
    "    'city_gp_hostel',\n",
    "    'city_coste_vida_estimado', 'city_quality_of_life',\n",
    "    'city_temp_media_anual', 'city_dias_sol_anual',\n",
    "    'city_beaches', 'city_parks', 'city_population_density',\n",
    "]\n",
    "\n",
    "feats_ok = [f for f in FEATURES_HEATMAP if f in num_df.columns]\n",
    "sub = num_df[feats_ok].copy()\n",
    "scaler_hm = MinMaxScaler()\n",
    "sub_norm = pd.DataFrame(scaler_hm.fit_transform(sub), index=sub.index, columns=sub.columns)\n",
    "\n",
    "# Ordenar ciudades por region para ver patrones geograficos\n",
    "orden = []\n",
    "for ciudades in REGIONES.values():\n",
    "    orden.extend([c for c in ciudades if c in sub_norm.index])\n",
    "orden.extend([c for c in sub_norm.index if c not in orden])\n",
    "sub_norm = sub_norm.loc[orden]\n",
    "\n",
    "short_feats = [c.replace('city_gp_','gp_').replace('city_','') for c in feats_ok]\n",
    "sub_norm.columns = short_feats\n",
    "\n",
    "fig, ax = plt.subplots(figsize=(18, 14))\n",
    "sns.heatmap(sub_norm, ax=ax, cmap='YlOrRd', vmin=0, vmax=1,\n",
    "            linewidths=0.2, linecolor='white',\n",
    "            cbar_kws={'shrink': 0.4, 'label': 'Valor normalizado [0-1]'})\n",
    "\n",
    "# Separadores por region\n",
    "pos = 0\n",
    "for region, ciudades in REGIONES.items():\n",
    "    n = len([c for c in ciudades if c in sub_norm.index])\n",
    "    if pos > 0:\n",
    "        ax.axhline(y=pos, color='white', linewidth=2)\n",
    "    ax.text(-0.5, pos + n/2, region, ha='right', va='center',\n",
    "            fontsize=8, color=COLORES_REGION[region], fontweight='bold',\n",
    "            transform=ax.get_yaxis_transform())\n",
    "    pos += n\n",
    "\n",
    "ax.set_title('Perfil de 55 ciudades x 28 features clave (normalizado 0-1)\\n'\n",
    "             'Amarillo claro = valor bajo. Rojo oscuro = valor alto',\n",
    "             fontweight='bold', pad=15)\n",
    "ax.set_xticklabels(ax.get_xticklabels(), rotation=45, ha='right', fontsize=9)\n",
    "plt.tight_layout()\n",
    "plt.savefig('../data/processed/eda_fase2_perfil_ciudades.png', dpi=150, bbox_inches='tight')\n",
    "plt.show()\n",
]))

cells.append(md([
    "```\n",
    "PARA QUE SIRVE ESTE GRAFICO:\n",
    "  Cada fila es una ciudad, cada columna es una feature. El color indica\n",
    "  el valor normalizado: amarillo = bajo (0), rojo = alto (1).\n",
    "  Si todas las filas fueran del mismo color, las ciudades serian\n",
    "  indistinguibles para el modelo. Los patrones de color son el 'perfil'\n",
    "  de cada ciudad.\n",
    "\n",
    "QUE NOS ESTA MOSTRANDO:\n",
    "  - Hay patrones claros por region: las ciudades europeas del norte tienen\n",
    "    columnas de surf/kite en amarillo (no tienen) y museos/historia en rojo.\n",
    "  - Tarifa y Fuerteventura destacan con rojo en surf/kite/windsurf y\n",
    "    amarillo en ski. El modelo las identificara correctamente.\n",
    "  - Chamonix e Innsbruck: rojo en ski, amarillo en surf. Perfil opuesto.\n",
    "  - Las ciudades latinoamericanas tienen rojo en coste bajo (coste_invertido)\n",
    "    y temperatura alta. Perfil coherente.\n",
    "  - Da_Nang (si aparece) deberia ser casi todo amarillo: confirma que\n",
    "    debe eliminarse del dataset.\n",
    "\n",
    "DECISION / IMPLICACION PARA EL MODELO:\n",
    "  - La existencia de patrones distintos entre ciudades es la condicion\n",
    "    necesaria para que el modelo funcione. Si todas fueran iguales,\n",
    "    ningun algoritmo podria hacer buenas recomendaciones.\n",
    "  - Los patrones geograficos visibles (clusters por region) sugieren que\n",
    "    la procedencia geografica es un proxy util pero que el modelo puede\n",
    "    ir mas alla y distinguir ciudades dentro de la misma region.\n",
    "```\n",
]))

# Paso 8: Radar charts
cells.append(md(["### Paso 8: Radar charts — perfil completo de ciudades representativas\n"]))

cells.append(code([
    "# Paso 8 — Radar charts: 8 ciudades representativas\n",
    "# Cada eje del radar es una de las 24 dimensiones del usuario.\n",
    "# El area del poligono muestra el 'perfil' de la ciudad.\n",
    "\n",
    "# Construir vector de dimension por ciudad (media de features de esa dimension)\n",
    "import sys\n",
    "sys.path.insert(0, str(Path('..')))\n",
    "from src.processing.features import DIMENSION_MAP\n",
    "\n",
    "scaler_radar = MinMaxScaler()\n",
    "num_norm_r = pd.DataFrame(\n",
    "    scaler_radar.fit_transform(num_df),\n",
    "    index=num_df.index, columns=num_df.columns\n",
    ")\n",
    "\n",
    "def ciudad_vector(ciudad, num_norm):\n",
    "    vec = {}\n",
    "    for dim_name, _, city_keys in DIMENSION_MAP:\n",
    "        cols_ok = [c for c in city_keys if c in num_norm.columns]\n",
    "        if cols_ok:\n",
    "            vec[dim_name] = num_norm.loc[ciudad, cols_ok].mean()\n",
    "        else:\n",
    "            vec[dim_name] = 0.0\n",
    "    return vec\n",
    "\n",
    "CIUDADES_RADAR = [\n",
    "    ('Tarifa',     '#EA4335'),\n",
    "    ('Chamonix',   '#4285F4'),\n",
    "    ('Barcelona',  '#FBBC05'),\n",
    "    ('Bangkok',    '#34A853'),\n",
    "    ('Tbilisi',    '#9C27B0'),\n",
    "    ('Berlin',     '#00BCD4'),\n",
    "    ('Medellin',   '#FF9800'),\n",
    "    ('Roma',       '#795548'),\n",
    "]\n",
    "\n",
    "dims   = [d[0] for d in DIMENSION_MAP]\n",
    "N      = len(dims)\n",
    "angles = [n / float(N) * 2 * np.pi for n in range(N)]\n",
    "angles += angles[:1]\n",
    "\n",
    "fig, axes = plt.subplots(2, 4, figsize=(20, 10), subplot_kw=dict(polar=True))\n",
    "axes_flat = axes.flatten()\n",
    "\n",
    "for ax, (ciudad, color) in zip(axes_flat, CIUDADES_RADAR):\n",
    "    if ciudad not in num_norm_r.index:\n",
    "        ax.set_visible(False)\n",
    "        continue\n",
    "    vec = ciudad_vector(ciudad, num_norm_r)\n",
    "    values = [vec[d] for d in dims] + [vec[dims[0]]]\n",
    "\n",
    "    ax.plot(angles, values, color=color, linewidth=2)\n",
    "    ax.fill(angles, values, color=color, alpha=0.2)\n",
    "    ax.set_xticks(angles[:-1])\n",
    "    ax.set_xticklabels(dims, size=7)\n",
    "    ax.set_ylim(0, 1)\n",
    "    ax.set_yticks([0.25, 0.5, 0.75])\n",
    "    ax.set_yticklabels(['0.25','0.5','0.75'], size=6, color='gray')\n",
    "    ax.set_title(ciudad, fontweight='bold', pad=15, color=color)\n",
    "\n",
    "fig.suptitle('Radar charts — perfil de 8 ciudades representativas\\n'\n",
    "             'Cada eje es una dimension del usuario (normalizada 0-1)',\n",
    "             fontweight='bold', fontsize=13)\n",
    "plt.tight_layout()\n",
    "plt.savefig('../data/processed/eda_fase2_radar_charts.png', dpi=150, bbox_inches='tight')\n",
    "plt.show()\n",
]))

cells.append(md([
    "```\n",
    "PARA QUE SIRVE ESTE GRAFICO:\n",
    "  Un radar chart (o grafico de tela de arana) muestra el perfil multidimensional\n",
    "  de una ciudad. Cada eje es una categoria de usuario (gastronomia, deporte,\n",
    "  cultura...). El area del poligono representa cuanto ofrece la ciudad en total.\n",
    "  Dos ciudades con poligonos similares son 'parecidas' para el modelo.\n",
    "\n",
    "QUE NOS ESTA MOSTRANDO:\n",
    "  - Tarifa: poligono concentrado en deporte_agua, naturaleza, clima.\n",
    "    Poco en cultura, familia, vida_nocturna. Perfil de especialista outdoor.\n",
    "  - Chamonix: poligono opuesto a Tarifa: alto en deporte_montana, bajo en surf.\n",
    "    Alta calidad de vida pero caro.\n",
    "  - Barcelona: poligono equilibrado y amplio — ciudad generalista con alto\n",
    "    en gastronomia, cultura, vida_nocturna, deporte_urbano.\n",
    "  - Tbilisi: destaca en coste bajo (coste_invertido alto) y cultura.\n",
    "    Perfecto para nomadas digitales con presupuesto ajustado.\n",
    "  - Medellin: similar a Tbilisi pero con mas bienestar y naturaleza.\n",
    "\n",
    "DECISION / IMPLICACION PARA EL MODELO:\n",
    "  - Los radar charts son el 'sanity check' definitivo: si Tarifa no destaca\n",
    "    en deporte_agua o Chamonix no destaca en deporte_montana, hay un error\n",
    "    en los datos o en las features.\n",
    "  - Este grafico sirve directamente para la presentacion del bootcamp:\n",
    "    muestra visualmente como el sistema 'entiende' cada ciudad.\n",
    "  - La Cosine Similarity (Capa 1) compara el poligono del usuario con el\n",
    "    poligono de cada ciudad y recomienda las mas parecidas.\n",
    "```\n",
]))

# ─────────────────────────────────────────────────────────────────────────────
# BLOQUE E — ESTRUCTURA Y CLUSTERING
# ─────────────────────────────────────────────────────────────────────────────
cells.append(md([
    "---\n",
    "## Bloque E — Estructura y clustering\n",
]))

# Setup normalizado para clustering
cells.append(code([
    "# Preparacion para clustering — normalizar y eliminar Da_Nang y features muertas\n",
    "\n",
    "FEATURES_MUERTAS = [\n",
    "    'city_gp_nature_reserve', 'city_gp_climbing_gym', 'city_gp_kayak',\n",
    "    'city_gp_tapas', 'city_gp_bicycle_rental', 'city_gp_mental_health',\n",
    "    'city_gp_scenic_point', 'city_gp_tour_operator',\n",
    "]\n",
    "\n",
    "# Excluir Da_Nang (datos practicamente todos ceros)\n",
    "df_cluster = num_df.drop(index=['Da_Nang'], errors='ignore')\n",
    "df_cluster = df_cluster.drop(columns=FEATURES_MUERTAS, errors='ignore')\n",
    "\n",
    "# Excluir features binarias (idioma, schengen) — no aportan distancia euclidea util\n",
    "binarias = [c for c in df_cluster.columns\n",
    "            if 'idioma' in c or c in ['city_schengen','city_moneda_eur']]\n",
    "df_cluster = df_cluster.drop(columns=binarias, errors='ignore')\n",
    "\n",
    "# Normalizar StandardScaler (media=0, std=1) para clustering\n",
    "# StandardScaler es mejor que MinMax para distancias porque no distorsiona outliers\n",
    "scaler_clust = StandardScaler()\n",
    "X_scaled = scaler_clust.fit_transform(df_cluster)\n",
    "ciudades_ok = df_cluster.index.tolist()\n",
    "\n",
    "print(f'Dataset para clustering: {len(ciudades_ok)} ciudades x {df_cluster.shape[1]} features')\n",
    "print(f'Excluidas: Da_Nang + {len(FEATURES_MUERTAS)} features muertas + {len(binarias)} binarias')\n",
]))

# Paso 9: PCA
cells.append(md(["### Paso 9: PCA — ¿qué features separan más las ciudades?\n"]))

cells.append(code([
    "# Paso 9 — PCA biplot\n",
    "# PCA (Principal Component Analysis) reduce las dimensiones manteniendo la\n",
    "# maxima varianza. Los primeros 2 componentes capturan la mayor separacion.\n",
    "\n",
    "pca = PCA(n_components=10, random_state=42)\n",
    "X_pca = pca.fit_transform(X_scaled)\n",
    "\n",
    "var_exp = pca.explained_variance_ratio_ * 100\n",
    "\n",
    "fig, axes = plt.subplots(1, 2, figsize=(18, 8))\n",
    "\n",
    "# --- Subplot 1: Scatter PCA coloreado por region ---\n",
    "ax1 = axes[0]\n",
    "for ciudad, x, y in zip(ciudades_ok, X_pca[:, 0], X_pca[:, 1]):\n",
    "    color = color_ciudad(ciudad)\n",
    "    ax1.scatter(x, y, color=color, s=80, zorder=3, alpha=0.85)\n",
    "    ax1.annotate(ciudad.replace('_',' '), (x, y),\n",
    "                 textcoords='offset points', xytext=(4, 3), fontsize=7)\n",
    "\n",
    "handles = [mpatches.Patch(color=c, label=r) for r, c in COLORES_REGION.items()]\n",
    "ax1.legend(handles=handles, fontsize=8, loc='upper right')\n",
    "ax1.set_xlabel(f'PC1 ({var_exp[0]:.1f}% varianza)', fontsize=11)\n",
    "ax1.set_ylabel(f'PC2 ({var_exp[1]:.1f}% varianza)', fontsize=11)\n",
    "ax1.set_title('PCA — ciudades en espacio reducido\\n(coloreado por region geografica)',\n",
    "              fontweight='bold')\n",
    "ax1.axhline(0, color='gray', alpha=0.3)\n",
    "ax1.axvline(0, color='gray', alpha=0.3)\n",
    "\n",
    "# --- Subplot 2: Varianza explicada acumulada ---\n",
    "ax2 = axes[1]\n",
    "var_cum = np.cumsum(var_exp)\n",
    "ax2.bar(range(1, 11), var_exp, color='#4285F4', alpha=0.7, label='Por componente')\n",
    "ax2.plot(range(1, 11), var_cum, 'o-', color='#EA4335', linewidth=2, label='Acumulada')\n",
    "ax2.axhline(80, color='gray', linestyle='--', alpha=0.5, label='80% umbral')\n",
    "for i, (v, vc) in enumerate(zip(var_exp, var_cum)):\n",
    "    ax2.text(i+1, v+0.5, f'{v:.1f}%', ha='center', fontsize=8)\n",
    "ax2.set_xlabel('Componente principal')\n",
    "ax2.set_ylabel('Varianza explicada (%)')\n",
    "ax2.set_title('Varianza explicada por componente', fontweight='bold')\n",
    "ax2.legend()\n",
    "ax2.set_xticks(range(1, 11))\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.savefig('../data/processed/eda_fase2_pca.png', dpi=150, bbox_inches='tight')\n",
    "plt.show()\n",
    "\n",
    "print(f'Varianza explicada por PC1+PC2: {var_exp[0]+var_exp[1]:.1f}%')\n",
    "n_para_80 = np.argmax(var_cum >= 80) + 1\n",
    "print(f'Componentes necesarios para 80% de varianza: {n_para_80}')\n",
]))

cells.append(md([
    "```\n",
    "PARA QUE SIRVE ESTE GRAFICO:\n",
    "  PCA (Analisis de Componentes Principales) proyecta las 130+ features en\n",
    "  solo 2 dimensiones manteniendo la maxima separacion posible entre ciudades.\n",
    "  Ciudades cercanas en el PCA son similares en sus datos. Ciudades alejadas\n",
    "  son muy distintas.\n",
    "  El grafico de varianza explicada muestra cuanta informacion del dataset\n",
    "  original captura cada componente.\n",
    "\n",
    "QUE NOS ESTA MOSTRANDO:\n",
    "  - Si PC1+PC2 explican >40% de varianza: hay estructura real en los datos.\n",
    "  - Las ciudades de la misma region tienden a agruparse, pero no perfectamente:\n",
    "    Barcelona y Berlin pueden estar cerca en el PCA aunque esten en distintas\n",
    "    partes de Europa si tienen features similares (cultura, vida nocturna, coworking).\n",
    "  - Tarifa y Fuerteventura deberian estar cerca (mismo perfil surf/kite).\n",
    "  - Chamonix e Innsbruck deberian estar cerca (mismo perfil ski).\n",
    "  - Si ciudades muy distintas estan cerca en el PCA, puede indicar un problema\n",
    "    en los datos.\n",
    "\n",
    "DECISION / IMPLICACION PARA EL MODELO:\n",
    "  - Si se necesitan muchos componentes (>8) para llegar al 80% de varianza,\n",
    "    los datos son de alta dimensionalidad real y PCA no simplifica mucho.\n",
    "  - El PCA se usa internamente en el pipeline de UserClusterer (PCA -> UMAP\n",
    "    -> HDBSCAN) para reducir ruido antes del clustering de usuarios.\n",
    "  - El biplot es el grafico mas valorado en entrevistas de ML para demostrar\n",
    "    que se entiende la estructura de los datos.\n",
    "```\n",
]))

# Paso 10: UMAP
cells.append(md(["### Paso 10: UMAP — similitud real entre ciudades\n"]))

cells.append(code([
    "# Paso 10 — UMAP: proyeccion no lineal que preserva estructura local\n",
    "# UMAP es mejor que PCA para visualizar clusters: mantiene vecinos cercanos juntos\n",
    "# aunque la distribucion global no sea lineal.\n",
    "\n",
    "reducer = umap.UMAP(\n",
    "    n_components=2,\n",
    "    n_neighbors=8,       # con 54 ciudades, vecindario pequeno\n",
    "    min_dist=0.3,\n",
    "    metric='euclidean',\n",
    "    random_state=42\n",
    ")\n",
    "X_umap = reducer.fit_transform(X_scaled)\n",
    "\n",
    "fig, ax = plt.subplots(figsize=(16, 11))\n",
    "\n",
    "for ciudad, (x, y) in zip(ciudades_ok, X_umap):\n",
    "    color = color_ciudad(ciudad)\n",
    "    ax.scatter(x, y, color=color, s=100, zorder=3, alpha=0.9, edgecolors='white', linewidth=0.5)\n",
    "    ax.annotate(ciudad.replace('_',' '), (x, y),\n",
    "                textcoords='offset points', xytext=(5, 4),\n",
    "                fontsize=8, alpha=0.9)\n",
    "\n",
    "handles = [mpatches.Patch(color=c, label=r) for r, c in COLORES_REGION.items()]\n",
    "ax.legend(handles=handles, fontsize=9, loc='upper right')\n",
    "ax.set_title('UMAP — similitud entre ciudades segun sus 130+ features\\n'\n",
    "             'Ciudades cercanas tienen perfil similar. Colores = region geografica.',\n",
    "             fontweight='bold', pad=12)\n",
    "ax.set_xlabel('UMAP dimension 1')\n",
    "ax.set_ylabel('UMAP dimension 2')\n",
    "ax.axis('off')\n",
    "plt.tight_layout()\n",
    "plt.savefig('../data/processed/eda_fase2_umap.png', dpi=150, bbox_inches='tight')\n",
    "plt.show()\n",
]))

cells.append(md([
    "```\n",
    "PARA QUE SIRVE ESTE GRAFICO:\n",
    "  UMAP (Uniform Manifold Approximation and Projection) es un algoritmo de\n",
    "  reduccion de dimensionalidad que preserva la estructura de vecindad:\n",
    "  si dos ciudades son similares en el espacio de 130+ features, aparecen\n",
    "  cerca en el UMAP. Es mas potente que PCA para detectar grupos no lineales.\n",
    "\n",
    "QUE NOS ESTA MOSTRANDO:\n",
    "  - Grupos naturales de ciudades similares: destinos de ski juntos,\n",
    "    ciudades de surf juntas, metropolis culturales juntas.\n",
    "  - Si el color (region geografica) coincide con la posicion en el UMAP,\n",
    "    significa que la ubicacion geografica es el factor dominante en los datos.\n",
    "  - Si hay ciudades de distintas regiones cerca en el UMAP, el modelo puede\n",
    "    descubrir similitudes que la geografia no captura (ej: Medellin cerca\n",
    "    de Tbilisi por ser baratas con buena calidad de vida).\n",
    "\n",
    "DECISION / IMPLICACION PARA EL MODELO:\n",
    "  - El UMAP con n_neighbors=8 es conservador para 54 ciudades. Con mas\n",
    "    ciudades (300+) los clusters emergerian con mas claridad.\n",
    "  - Este grafico justifica visualmente la decision de eliminar el City\n",
    "    Clustering (Capa 3) del MVP: si el UMAP no muestra grupos bien definidos,\n",
    "    el clustering forzado seria arbitrario.\n",
    "  - La Cosine Similarity (Capa 1) usa la misma informacion que el UMAP\n",
    "    pero de forma continua, sin necesidad de asignar clusters.\n",
    "```\n",
]))

# Paso 11: Dendrograma
cells.append(md(["### Paso 11: Dendrograma — agrupaciones jerárquicas naturales\n"]))

cells.append(code([
    "# Paso 11 — Dendrograma: clustering jerarquico agglomerativo\n",
    "# El dendrograma muestra como se van agrupando las ciudades de abajo a arriba.\n",
    "# No necesitamos decidir el numero de clusters de antemano.\n",
    "\n",
    "linkage_matrix = linkage(X_scaled, method='ward', metric='euclidean')\n",
    "\n",
    "fig, ax = plt.subplots(figsize=(16, 9))\n",
    "colores_dendro = [color_ciudad(c) for c in ciudades_ok]\n",
    "\n",
    "dendrogram(\n",
    "    linkage_matrix,\n",
    "    labels=ciudades_ok,\n",
    "    ax=ax,\n",
    "    leaf_rotation=90,\n",
    "    leaf_font_size=8,\n",
    "    color_threshold=linkage_matrix[-4, 2],  # colorear los 4 cortes principales\n",
    ")\n",
    "\n",
    "ax.set_title('Dendrograma — clustering jerarquico de 54 ciudades\\n'\n",
    "             '(Ward linkage, distancia Euclidea sobre 130+ features normalizadas)',\n",
    "             fontweight='bold', pad=12)\n",
    "ax.set_ylabel('Distancia de fusion (Ward)')\n",
    "ax.set_xlabel('Ciudad')\n",
    "\n",
    "# Linea de corte sugerida\n",
    "threshold = linkage_matrix[-5, 2]\n",
    "ax.axhline(y=threshold, color='red', linestyle='--', alpha=0.6,\n",
    "           label=f'Corte sugerido (~5 grupos)')\n",
    "ax.legend(fontsize=9)\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.savefig('../data/processed/eda_fase2_dendrograma.png', dpi=150, bbox_inches='tight')\n",
    "plt.show()\n",
]))

cells.append(md([
    "```\n",
    "PARA QUE SIRVE ESTE GRAFICO:\n",
    "  Un dendrograma muestra el proceso de clustering jerarquico: empieza con\n",
    "  cada ciudad como su propio cluster y va fusionando los mas similares.\n",
    "  Las ciudades al fondo de la misma 'rama' son las mas parecidas entre si.\n",
    "  La altura del punto de fusion indica que tan distintos eran los grupos\n",
    "  cuando se unieron: fusiones bajas = grupos muy similares.\n",
    "\n",
    "QUE NOS ESTA MOSTRANDO:\n",
    "  - Grupos esperados: Tarifa/Fuerteventura/Dakhla juntas (surf/kite).\n",
    "    Chamonix/Innsbruck/Andorra juntas (ski/montana).\n",
    "    Grandes metropolis culturales (Barcelona/Paris/Roma) en otra rama.\n",
    "  - Si la altura del dendrograma es alta en todos los cortes, significa\n",
    "    que los grupos son poco compactos — las ciudades dentro de cada grupo\n",
    "    son heterogeneas.\n",
    "  - El corte horizontal rojo sugiere donde 'cortar' para obtener N grupos.\n",
    "\n",
    "DECISION / IMPLICACION PARA EL MODELO:\n",
    "  - El dendrograma es exploratorio: nos ayuda a ver si hay estructura\n",
    "    jerarquica natural en los datos antes de aplicar k-means o HDBSCAN.\n",
    "  - Si los grupos son poco compactos (ramas altas), confirma que con 54\n",
    "    ciudades no hay suficiente masa critica para clustering estable.\n",
    "  - Este es el argumento visual para justificar que la Capa 3 (city\n",
    "    clustering) se elimina del MVP y se retoma cuando haya 300+ ciudades.\n",
    "```\n",
]))

# Paso 12: KMeans + HDBSCAN
cells.append(md(["### Paso 12: Intento de clustering — ¿hay clusters claros con 54 ciudades?\n"]))

cells.append(code([
    "# Paso 12 — Intentar K-Means y HDBSCAN sobre las ciudades\n",
    "# Objetivo: mostrar que con 54 ciudades no emergen clusters estables.\n",
    "# Esto justifica la decision de eliminar la Capa 3 del MVP.\n",
    "\n",
    "# ── K-Means: probar distintos K ───────────────────────────────────────────\n",
    "print('=== K-MEANS: busqueda de K optimo ===')\n",
    "ks = range(2, 10)\n",
    "silhouette_scores = []\n",
    "db_scores = []\n",
    "inertias = []\n",
    "\n",
    "for k in ks:\n",
    "    km = KMeans(n_clusters=k, random_state=42, n_init=10)\n",
    "    labels = km.fit_predict(X_scaled)\n",
    "    sil = silhouette_score(X_scaled, labels)\n",
    "    db  = davies_bouldin_score(X_scaled, labels)\n",
    "    silhouette_scores.append(sil)\n",
    "    db_scores.append(db)\n",
    "    inertias.append(km.inertia_)\n",
    "    print(f'  K={k}: Silhouette={sil:.3f} | Davies-Bouldin={db:.3f} | Inercia={km.inertia_:.0f}')\n",
    "\n",
    "print()\n",
    "print('Silhouette: rango [-1,+1]. Mas alto = clusters mas compactos y separados.')\n",
    "print('Davies-Bouldin: mas bajo = clusters mejor definidos.')\n",
    "print(f'Mejor K por Silhouette: {ks[np.argmax(silhouette_scores)]}')\n",
    "\n",
    "# ── HDBSCAN ───────────────────────────────────────────────────────────────\n",
    "print()\n",
    "print('=== HDBSCAN ===')\n",
    "hdb = hdbscan.HDBSCAN(min_cluster_size=3, min_samples=2, metric='euclidean')\n",
    "labels_hdb = hdb.fit_predict(X_scaled)\n",
    "n_clusters_hdb = len(set(labels_hdb)) - (1 if -1 in labels_hdb else 0)\n",
    "n_noise = (labels_hdb == -1).sum()\n",
    "print(f'Clusters encontrados: {n_clusters_hdb}')\n",
    "print(f'Ciudades sin cluster (ruido): {n_noise}/{len(ciudades_ok)}')\n",
    "if n_clusters_hdb > 0:\n",
    "    for k in range(n_clusters_hdb):\n",
    "        members = [c for c, l in zip(ciudades_ok, labels_hdb) if l == k]\n",
    "        print(f'  Cluster {k}: {members}')\n",
]))

cells.append(code([
    "# Visualizacion: metricas K-Means y UMAP coloreado por cluster\n",
    "\n",
    "fig, axes = plt.subplots(1, 3, figsize=(20, 6))\n",
    "\n",
    "# --- Silhouette ---\n",
    "axes[0].plot(list(ks), silhouette_scores, 'o-', color='#4285F4', linewidth=2)\n",
    "axes[0].set_xlabel('Numero de clusters (K)')\n",
    "axes[0].set_ylabel('Silhouette Score')\n",
    "axes[0].set_title('K-Means: Silhouette Score\\n(mayor = mejor separacion)', fontweight='bold')\n",
    "axes[0].set_xticks(list(ks))\n",
    "best_k_idx = np.argmax(silhouette_scores)\n",
    "axes[0].axvline(x=list(ks)[best_k_idx], color='#EA4335', linestyle='--', alpha=0.7,\n",
    "                label=f'Mejor K={list(ks)[best_k_idx]}')\n",
    "axes[0].legend()\n",
    "\n",
    "# --- Davies-Bouldin ---\n",
    "axes[1].plot(list(ks), db_scores, 'o-', color='#EA4335', linewidth=2)\n",
    "axes[1].set_xlabel('Numero de clusters (K)')\n",
    "axes[1].set_ylabel('Davies-Bouldin Score')\n",
    "axes[1].set_title('K-Means: Davies-Bouldin\\n(menor = mejor separacion)', fontweight='bold')\n",
    "axes[1].set_xticks(list(ks))\n",
    "\n",
    "# --- UMAP coloreado por mejor K ---\n",
    "best_k = list(ks)[best_k_idx]\n",
    "km_best = KMeans(n_clusters=best_k, random_state=42, n_init=10)\n",
    "labels_best = km_best.fit_predict(X_scaled)\n",
    "cmap_k = cm.get_cmap('tab10', best_k)\n",
    "\n",
    "for ciudad, (x, y), label in zip(ciudades_ok, X_umap, labels_best):\n",
    "    color = cmap_k(label)\n",
    "    axes[2].scatter(x, y, color=color, s=90, zorder=3, alpha=0.85,\n",
    "                    edgecolors='white', linewidth=0.5)\n",
    "    axes[2].annotate(ciudad.replace('_',' '), (x, y),\n",
    "                     textcoords='offset points', xytext=(4, 3), fontsize=7)\n",
    "axes[2].set_title(f'UMAP coloreado por K-Means (K={best_k})\\n'\n",
    "                  '¿Los clusters tienen sentido semantico?', fontweight='bold')\n",
    "axes[2].axis('off')\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.savefig('../data/processed/eda_fase2_clustering.png', dpi=150, bbox_inches='tight')\n",
    "plt.show()\n",
]))

cells.append(md([
    "```\n",
    "PARA QUE SIRVE ESTE GRAFICO:\n",
    "  Mide formalmente si los clusters de ciudades son 'buenos' o arbitrarios.\n",
    "  Silhouette Score: va de -1 a +1. Por encima de 0.5 = clusters compactos\n",
    "  y bien separados. Por debajo de 0.3 = clusters poco definidos.\n",
    "  Davies-Bouldin: cuanto mas bajo, mejor. Mide la dispersion intra-cluster\n",
    "  vs la separacion inter-cluster.\n",
    "  El UMAP coloreado por K permite ver si los clusters tienen sentido semantico.\n",
    "\n",
    "QUE NOS ESTA MOSTRANDO:\n",
    "  - Si el Silhouette Score es bajo (<0.3 para todos los K): no hay estructura\n",
    "    de clusters clara con 54 ciudades. Los grupos son arbitrarios.\n",
    "  - En el UMAP coloreado: si ciudades muy distintas (Tarifa y Berlin) quedan\n",
    "    en el mismo cluster, el clustering no aporta informacion util.\n",
    "  - HDBSCAN con min_cluster_size=3 puede encontrar algunos grupos naturales\n",
    "    (ski, surf) pero la mayoria de ciudades quedan como 'ruido' (-1).\n",
    "    Con 54 ciudades es dificil que HDBSCAN encuentre clusters estables.\n",
    "\n",
    "DECISION / IMPLICACION PARA EL MODELO — DECISION CRITICA:\n",
    "  Esta es la justificacion empirica para eliminar la Capa 3 (City Clustering)\n",
    "  del MVP:\n",
    "  - Con Fuzzy C-Means se obtuvo FPC=0.033 (el minimo posible = sin estructura).\n",
    "  - K-Means y HDBSCAN confirman lo mismo: Silhouette bajo, clusters sin\n",
    "    coherencia semantica con 54 ciudades.\n",
    "  - La Cosine Similarity (Capa 1) reemplaza el city clustering:\n",
    "    en lugar de asignar ciudades a grupos rigidos, calcula similitud continua\n",
    "    con el perfil del usuario. Es mas preciso y no requiere un numero minimo\n",
    "    de ciudades.\n",
    "  - Cuando el dataset crezca a 300+ ciudades, el city clustering se revisara.\n",
    "```\n",
]))

# ─────────────────────────────────────────────────────────────────────────────
# RESUMEN FASE 2
# ─────────────────────────────────────────────────────────────────────────────
cells.append(md([
    "---\n",
    "## Resumen de Fase 2\n",
]))

cells.append(code([
    "print('=== RESUMEN FASE 2: QUE NOS DICEN LOS DATOS ===')\n",
    "print()\n",
    "print('BLOQUE A — Estadisticas basicas:')\n",
    "print('  - Escalas muy distintas entre features (necesita normalizacion)')\n",
    "print('  - Alta variabilidad en coste (700-2100 EUR) y clima (5-28 C): bueno para el modelo')\n",
    "print('  - internet_mbps sesgado por 43 ceros (dato ausente, no velocidad cero)')\n",
    "print()\n",
    "print('BLOQUE B — Distribuciones:')\n",
    "print('  - Features especializadas (ski, kite) tienen distribucion en cola: ideal para diferenciar')\n",
    "print('  - Features genericas (restaurantes, gimnasios) mas uniformes: menor poder diferenciador')\n",
    "print('  - Boxplots confirman outliers esperados (Tarifa en surf, Chamonix en ski)')\n",
    "print()\n",
    "print('BLOQUE C — Relaciones:')\n",
    "print('  - coste y alquiler correlados (esperado). Ski y temperatura correlados negativamente (correcto)')\n",
    "print('  - Existen outliers valor: ciudades baratas con buena calidad (Tbilisi, Medellin)')\n",
    "print()\n",
    "print('BLOQUE D — Perfil de ciudades:')\n",
    "print('  - Heatmap: ciudades claramente distinguibles — el modelo tiene estructura para aprender')\n",
    "print('  - Radar charts: sanity check positivo — Tarifa destaca en surf, Chamonix en ski')\n",
    "print()\n",
    "print('BLOQUE E — Clustering:')\n",
    "print('  - PCA: hay estructura pero dispersa — se necesitan varios componentes para 80% varianza')\n",
    "print('  - UMAP: grupos naturales visibles (ski, surf, metropolis) pero fronteras difusas')\n",
    "print('  - Dendrograma: agrupaciones jerarquicas coherentes en algunos casos')\n",
    "print('  - K-Means + HDBSCAN: Silhouette bajo — confirma que el city clustering no es viable')\n",
    "print('    con 54 ciudades. Decision: Cosine Similarity reemplaza Capa 3 en MVP')\n",
    "print()\n",
    "print('SIGUIENTE PASO: Fase 3 — EDA de Arquetipos (previa aprobacion)')\n",
]))

cells.append(md([
    "```\n",
    "CONCLUSION GENERAL — FASE 2:\n",
    "\n",
    "PARA EL MODELO:\n",
    "  1. Los datos tienen estructura suficiente para el modelo: las ciudades son\n",
    "     distinguibles y las features especializadas diferencian bien los destinos.\n",
    "  2. Acciones antes de entrenar:\n",
    "     - Eliminar Da_Nang (todos ceros)\n",
    "     - Eliminar las 8 features completamente vacias\n",
    "     - Imputar o eliminar city_internet_mbps (43 ceros no son velocidad cero)\n",
    "  3. El city clustering (Capa 3) no es viable con 54 ciudades.\n",
    "     La Cosine Similarity (Capa 1) es la alternativa correcta para el MVP.\n",
    "\n",
    "PARA LA PRESENTACION:\n",
    "  - El radar chart de ciudades es el grafico mas impactante para mostrar\n",
    "    como el sistema entiende cada destino.\n",
    "  - El scatter coste vs calidad demuestra que el modelo puede encontrar\n",
    "    'joyas ocultas' que el usuario no conoceria de otra manera.\n",
    "  - El UMAP + clustering demuestra rigor: se probo clustering y se documento\n",
    "    por que no funciona con el dataset actual. Eso es ML honesto.\n",
    "\n",
    "SIGUIENTE PASO:\n",
    "  Fase 3 — EDA de Arquetipos: validar que los 21 arquetipos estan bien\n",
    "  diferenciados entre si antes de generar perfiles sinteticos.\n",
    "  No avanzar sin consultar y recibir aprobacion.\n",
    "```\n",
]))

# ─────────────────────────────────────────────────────────────────────────────
# GUARDAR
# ─────────────────────────────────────────────────────────────────────────────
nb = {
    "cells": cells,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3 (.venv)",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "name": "python",
            "pygments_lexer": "ipython3",
            "version": "3.12.10"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 5
}

out = ROOT / "notebooks" / "01b_eda_fase2_ciudades.ipynb"
with open(out, "w", encoding="utf-8") as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)

print(f"Notebook creado: {out}")
print(f"Total celdas: {len(cells)}")
